// <auto-generated />
namespace Clinic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Meg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meg));
        
        string IMigrationMetadata.Id
        {
            get { return "202508311934504_Meg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
